version: '3.8'
services:
  taxcalculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxcalculator
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/employee_tax
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres_password
    networks:
      - backend

  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: postgres_emp
    environment:
      POSTGRES_DB: employee_tax
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
