server:
  port: 8080

spring:
  application:
    name=taxcalculator
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/employee_tax
    username: postgres
    password: postgres_password
    driver-class-name: org.postgresql.Driver